---
type: yml
auth:
  sign_key: jwt_secret

http_server:
  port: 8088

mysql:
  host: localhost
  port: 3308
  db_name: gameapp_db
  username: gameapp
  password: gameappt0lk2o20
redis:
  host: localhost
  port: 6380
  password: ""
  db: 0
matching_service:
  waitingTimeOut: "2m"

