version: '3.7'

services:
  gameapp-database:
    image: mysql:8.0
    ports:
      - "3308:3306"
    container_name: gameapp-database
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    command: ['mysqld',
              '--character-set-server=utf8mb4',
              '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}


volumes:
  dbdata:
