services:
  gameapp-database:
    image: mysql:8.0
    ports:
      - "3308:3306"
    container_name: gameapp-database
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    command: ['mysqld',
              '--character-set-server=utf8mb4',
              '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  radis-db:
    image: redis:6.2-alpine
    restart: always
    container_name: radis-db
    ports:
      - '6380:6379'
    command: redis-server --loglevel warning
    volumes:
      - radis-db:/data

volumes:
  dbdata:
  radis-db:
